-- Ćwiczenie 1A
CREATE TABLE A6_LRS (
    GEOM SDO_GEOMETRY
);

-- Ćwiczenie 1B
INSERT INTO A6_LRS
SELECT SR.GEOM
FROM STREETS_AND_RAILROADS SR
WHERE SR.ID = (
    SELECT SR.ID
    FROM STREETS_AND_RAILROADS SR, MAJOR_CITIES M
    WHERE SDO_RELATE(SR.GEOM,SDO_GEOM.SDO_BUFFER(M.GEOM, 10, 1, 'unit=km'), 'mask=ANYINTERACT') = 'TRUE'
    AND M.CITY_NAME = 'Koszalin'
);

-- Ćwiczenie 1C
SELECT 
    SDO_GEOM.SDO_LENGTH(A6.GEOM, 1, 'unit=km') AS DISTANCE,
    ST_LINESTRING(A6.GEOM).ST_NUMPOINTS() AS ST_NUMPOINTS
FROM A6_LRS A6;

-- Ćwiczenie 1D
UPDATE A6_LRS A6
SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(A6.GEOM, 0, 276.681315399186);

-- Ćwiczenie 1E
INSERT INTO USER_SDO_GEOM_METADATA 
VALUES (
    'A6_LRS',
    'GEOM',
    MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
    MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1)),
    8307
);

-- Ćwiczenie 1F
CREATE INDEX A6_IDX
ON A6_LRS(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- Ćwiczenie 2A
SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) AS VALID_500
FROM A6_LRS;

-- Ćwiczenie 2B
SELECT SDO_LRS.GEOM_SEGMENT_END_PT(A6.GEOM) AS END_PT
FROM A6_LRS A6;

-- Ćwiczenie 2C
SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) AS KM150
FROM A6_LRS;

-- Ćwiczenie 2D
SELECT SDO_LRS.CLIP_GEOM_SEGMENT(A6.GEOM, 120, 160) AS CLIPPED
FROM A6_LRS A6;

-- Ćwiczenie 2E
SELECT SDO_LRS.GET_NEXT_SHAPE_PT(A6.GEOM, M.GEOM) AS WJAZD_NA_A6
FROM A6_LRS A6, MAJOR_CITIES M
WHERE M.CITY_NAME = 'Slupsk';

-- Ćwiczenie 2F
SELECT SDO_GEOM.SDO_LENGTH(
        SDO_LRS.OFFSET_GEOM_SEGMENT(
            A6.GEOM, M.DIMINFO, 50, 200, 50, 'unit=m'), 1, 'unit=km') KOSZT_W_MLN
FROM A6_LRS A6, USER_SDO_GEOM_METADATA M
WHERE M.TABLE_NAME = 'A6_LRS'
AND M.COLUMN_NAME = 'GEOM';
